cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -qq && apt-get install

stages:
  - build
  - deploy

build:
  image: node:latest

  stage: build
  variables:
    # Replace this with your site URL
    PUBLIC_URL: https://mortalwombat.gitlab.io/scrimsight/
    NODE_ENV: production
  before_script:
    - ls
    - npm list -g --depth 0
    - npm install -g webpack webpack-cli
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - build/

pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none # Do not clone git repo
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public
  artifacts:
    paths:
      - public
  # only: [master]
