# cache:
#   paths:
#     - node_modules/

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  image: ubuntu:20.04

  stage: build
  variables:
    # Replace this with your site URL
    PUBLIC_URL: '/scrimsight'
    NODE_ENV: 'production'
    # TS_NODE_COMPILER_OPTIONS: '{"module": "commonjs"}'
    # NODE_OPTIONS: '--loader ts-node/esm'
  before_script:
    - printenv
    - ls
    - apt-get update -qq && apt-get install
    # - npm install -g webpack webpack-cli ts-node
    # - npmlist -g --depth 0
    # - npm config get production
    - apt install curl -y
    - curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
    - source ~/.bashrc
    - export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" --no-use #load nvm
    - eval "[ -f .nvmrc ] && nvm install || nvm install node" #install node
    - npm ci
    - npm list
    # - npm install webpack -g
    # - npx webpack --profile --json=test.json
    # - npm list --depth 0
  script:
    - unset CI
    - npm run build
  artifacts:
    paths:
      - build/

pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none # Do not clone git repo
  script:
    # Rename the CRA `build` folder to `public`
    - cp public/assets public/assets
    - mv build public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  # only: [master]
