# cache:
#   paths:
#     - node_modules/

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  image: ubuntu:20.04

  stage: build
  variables:
    PUBLIC_URL: '/'
    NODE_ENV: 'production'
  before_script:
    - apt-get update -qq && apt-get install
    - apt install curl -y
    - curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
    - source ~/.bashrc
    - export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" --no-use #load nvm
    - eval "[ -f .nvmrc ] && nvm install || nvm install node" #install node
    - npm ci
    - mkdir build
  script:
    - unset CI
    - npm run build
    - cp -r public/assets build/assets
  artifacts:
    paths:
      - build/
      - public/

pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none # Do not clone git repo
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  # only: [master]
