cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  image: node:latest

  stage: build
  variables:
    # Replace this with your site URL
    PUBLIC_URL: https://mortalwombat.gitlab.io/scrimsight/
    NODE_ENV: production
    # TS_NODE_COMPILER_OPTIONS: '{"module": "commonjs"}'
    # NODE_OPTIONS: '--loader ts-node/esm'
  before_script:
    - ls
    # - apt-get update -qq && apt-get install
    # - npm install -g webpack webpack-cli ts-node
    # - npmlist -g --depth 0
    # - npm config get production
    - npm install
    # - npm install webpack -g
    # - npx webpack --profile --json=test.json
    # - npm list --depth 0
  script:
    - npm run build
  artifacts:
    paths:
      - build/

pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none # Do not clone git repo
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public
  artifacts:
    paths:
      - public
  # only: [master]
