import { AtomCollection } from '~/pages/SchemaVisualizer/types';

/**
 * Extract atoms and their dependencies from the codebase
 * This is a mock implementation - in a real scenario, you would:
 * 1. Parse actual atom files
 * 2. Extract dependencies
 * 3. Build the relationship graph
 */
export const getAtomData = async (): Promise<AtomCollection> => {
  // This would ideally be generated by analyzing the codebase
  // For now, we'll create a simplified representation of the schema
  return {
    atoms: [
      // Data Loading Atoms
      {
        id: 'logFileInputAtom',
        label: 'logFileInputAtom',
        type: 'atom<File[]>',
        layer: 'data',
        fields: [
          { name: 'files', type: 'File[]' }
        ]
      },
      {
        id: 'logFileLoaderAtom',
        label: 'logFileLoaderAtom',
        type: 'atom<string[]>',
        layer: 'data',
        fields: [
          { name: 'loadedFiles', type: 'string[]' }
        ]
      },
      {
        id: 'logFileParserAtom',
        label: 'logFileParserAtom',
        type: 'atom<ParsedLogData[]>',
        layer: 'data',
        fields: [
          { name: 'parsedData', type: 'ParsedLogData[]' }
        ]
      },
      {
        id: 'matchDataAtom',
        label: 'matchDataAtom',
        type: 'atom<MatchData[]>',
        layer: 'data',
        fields: [
          { name: 'matches', type: 'MatchData[]' }
        ]
      },
      
      // Event Extractor Atoms
      {
        id: 'killExtractorAtom',
        label: 'killExtractorAtom',
        type: 'atom<KillEvent[]>',
        layer: 'extractor',
        fields: [
          { name: 'kills', type: 'KillEvent[]' }
        ]
      },
      {
        id: 'ultimateStartExtractorAtom',
        label: 'ultimateStartExtractorAtom',
        type: 'atom<UltimateStartEvent[]>',
        layer: 'extractor',
        fields: [
          { name: 'ultimateStarts', type: 'UltimateStartEvent[]' }
        ]
      },
      {
        id: 'ultimateEndExtractorAtom',
        label: 'ultimateEndExtractorAtom',
        type: 'atom<UltimateEndEvent[]>',
        layer: 'extractor',
        fields: [
          { name: 'ultimateEnds', type: 'UltimateEndEvent[]' }
        ]
      },
      {
        id: 'heroSpawnExtractorAtom',
        label: 'heroSpawnExtractorAtom',
        type: 'atom<HeroSpawnEvent[]>',
        layer: 'extractor',
        fields: [
          { name: 'heroSpawns', type: 'HeroSpawnEvent[]' }
        ]
      },
      {
        id: 'heroSwapExtractorAtom',
        label: 'heroSwapExtractorAtom',
        type: 'atom<HeroSwapEvent[]>',
        layer: 'extractor',
        fields: [
          { name: 'heroSwaps', type: 'HeroSwapEvent[]' }
        ]
      },
      {
        id: 'defensiveAssistExtractorAtom',
        label: 'defensiveAssistExtractorAtom',
        type: 'atom<DefensiveAssistEvent[]>',
        layer: 'extractor',
        fields: [
          { name: 'defensiveAssists', type: 'DefensiveAssistEvent[]' }
        ]
      },
      {
        id: 'offensiveAssistExtractorAtom',
        label: 'offensiveAssistExtractorAtom',
        type: 'atom<OffensiveAssistEvent[]>',
        layer: 'extractor',
        fields: [
          { name: 'offensiveAssists', type: 'OffensiveAssistEvent[]' }
        ]
      },
      
      // Derived Events Atoms
      {
        id: 'playerEventsAtom',
        label: 'playerEventsAtom',
        type: 'atom<PlayerEvent[]>',
        layer: 'derived_event',
        fields: [
          { name: 'events', type: 'PlayerEvent[]' }
        ]
      },
      {
        id: 'playerInteractionEventsAtom',
        label: 'playerInteractionEventsAtom',
        type: 'atom<PlayerInteractionEvent[]>',
        layer: 'derived_event',
        fields: [
          { name: 'interactions', type: 'PlayerInteractionEvent[]' }
        ]
      },
      {
        id: 'ultimateEventsAtom',
        label: 'ultimateEventsAtom',
        type: 'atom<UltimateEvent[]>',
        layer: 'derived_event',
        fields: [
          { name: 'ultimates', type: 'UltimateEvent[]' }
        ]
      },
      
      // Derived State Atoms
      {
        id: 'playerStatusTimelineAtom',
        label: 'playerStatusTimelineAtom',
        type: 'atom<PlayerStatusTimeline>',
        layer: 'derived_state',
        fields: [
          { name: 'timeline', type: 'PlayerStatusTimeline' }
        ]
      },
      {
        id: 'teamfightsAtom',
        label: 'teamfightsAtom',
        type: 'atom<Teamfight[]>',
        layer: 'derived_state',
        fields: [
          { name: 'teamfights', type: 'Teamfight[]' }
        ]
      },
      {
        id: 'playerLivesAtom',
        label: 'playerLivesAtom',
        type: 'atom<PlayerLife[]>',
        layer: 'derived_state',
        fields: [
          { name: 'lives', type: 'PlayerLife[]' }
        ]
      },
      
      // Derived Stats Atoms
      {
        id: 'killMatrixAtom',
        label: 'killMatrixAtom',
        type: 'atomFamily<KillMatrixData>',
        layer: 'derived_stats',
        fields: [
          { name: 'killMatrix', type: 'KillMatrixData' }
        ]
      },
      {
        id: 'firstKillImpactAtom',
        label: 'firstKillImpactAtom',
        type: 'atom<FirstKillImpact[]>',
        layer: 'derived_stats',
        fields: [
          { name: 'firstKillImpact', type: 'FirstKillImpact[]' }
        ]
      },
      {
        id: 'ultimateImpactAtom',
        label: 'ultimateImpactAtom',
        type: 'atom<UltimateImpact[]>',
        layer: 'derived_stats',
        fields: [
          { name: 'ultimateImpact', type: 'UltimateImpact[]' }
        ]
      },
      {
        id: 'teamfightParticipationAtom',
        label: 'teamfightParticipationAtom',
        type: 'atom<TeamfightParticipation[]>',
        layer: 'derived_stats',
        fields: [
          { name: 'participation', type: 'TeamfightParticipation[]' }
        ]
      },
      
      // Metrics Atoms
      {
        id: 'playerMetricsAtoms',
        label: 'playerMetricsAtoms',
        type: 'atom<PlayerMetrics[]>',
        layer: 'metrics',
        fields: [
          { name: 'metrics', type: 'PlayerMetrics[]' }
        ]
      },
      {
        id: 'heroPlaytimeAtom',
        label: 'heroPlaytimeAtom',
        type: 'atom<HeroPlaytime[]>',
        layer: 'metrics',
        fields: [
          { name: 'playtime', type: 'HeroPlaytime[]' }
        ]
      },
      {
        id: 'teamStatsAtom',
        label: 'teamStatsAtom',
        type: 'atom<TeamStats[]>',
        layer: 'metrics',
        fields: [
          { name: 'stats', type: 'TeamStats[]' }
        ]
      },
    ],
    dependencies: [
      // Data Loading Dependencies
      {
        sourceAtom: 'logFileInputAtom',
        sourceField: 'files',
        targetAtom: 'logFileLoaderAtom',
        targetField: 'loadedFiles',
        label: 'loads'
      },
      {
        sourceAtom: 'logFileLoaderAtom',
        sourceField: 'loadedFiles',
        targetAtom: 'logFileParserAtom',
        targetField: 'parsedData',
        label: 'parses'
      },
      {
        sourceAtom: 'logFileParserAtom',
        sourceField: 'parsedData',
        targetAtom: 'matchDataAtom',
        targetField: 'matches',
        label: 'extracts'
      },
      
      // Event Extractor Dependencies
      {
        sourceAtom: 'logFileParserAtom',
        sourceField: 'parsedData',
        targetAtom: 'killExtractorAtom',
        targetField: 'kills',
        label: 'extracts'
      },
      {
        sourceAtom: 'logFileParserAtom',
        sourceField: 'parsedData',
        targetAtom: 'ultimateStartExtractorAtom',
        targetField: 'ultimateStarts',
        label: 'extracts'
      },
      {
        sourceAtom: 'logFileParserAtom',
        sourceField: 'parsedData',
        targetAtom: 'ultimateEndExtractorAtom',
        targetField: 'ultimateEnds',
        label: 'extracts'
      },
      {
        sourceAtom: 'logFileParserAtom',
        sourceField: 'parsedData',
        targetAtom: 'heroSpawnExtractorAtom',
        targetField: 'heroSpawns',
        label: 'extracts'
      },
      {
        sourceAtom: 'logFileParserAtom',
        sourceField: 'parsedData',
        targetAtom: 'heroSwapExtractorAtom',
        targetField: 'heroSwaps',
        label: 'extracts'
      },
      {
        sourceAtom: 'logFileParserAtom',
        sourceField: 'parsedData',
        targetAtom: 'defensiveAssistExtractorAtom',
        targetField: 'defensiveAssists',
        label: 'extracts'
      },
      {
        sourceAtom: 'logFileParserAtom',
        sourceField: 'parsedData',
        targetAtom: 'offensiveAssistExtractorAtom',
        targetField: 'offensiveAssists',
        label: 'extracts'
      },
      
      // Derived Events Dependencies
      {
        sourceAtom: 'heroSpawnExtractorAtom',
        sourceField: 'heroSpawns',
        targetAtom: 'playerEventsAtom',
        targetField: 'events',
        label: 'combines'
      },
      {
        sourceAtom: 'heroSwapExtractorAtom',
        sourceField: 'heroSwaps',
        targetAtom: 'playerEventsAtom',
        targetField: 'events',
        label: 'combines'
      },
      {
        sourceAtom: 'defensiveAssistExtractorAtom',
        sourceField: 'defensiveAssists',
        targetAtom: 'playerEventsAtom',
        targetField: 'events',
        label: 'combines'
      },
      {
        sourceAtom: 'offensiveAssistExtractorAtom',
        sourceField: 'offensiveAssists',
        targetAtom: 'playerEventsAtom',
        targetField: 'events',
        label: 'combines'
      },
      {
        sourceAtom: 'killExtractorAtom',
        sourceField: 'kills',
        targetAtom: 'playerInteractionEventsAtom',
        targetField: 'interactions',
        label: 'combines'
      },
      {
        sourceAtom: 'defensiveAssistExtractorAtom',
        sourceField: 'defensiveAssists',
        targetAtom: 'playerInteractionEventsAtom',
        targetField: 'interactions',
        label: 'combines'
      },
      {
        sourceAtom: 'offensiveAssistExtractorAtom',
        sourceField: 'offensiveAssists',
        targetAtom: 'playerInteractionEventsAtom',
        targetField: 'interactions',
        label: 'combines'
      },
      {
        sourceAtom: 'ultimateStartExtractorAtom',
        sourceField: 'ultimateStarts',
        targetAtom: 'ultimateEventsAtom',
        targetField: 'ultimates',
        label: 'combines'
      },
      {
        sourceAtom: 'ultimateEndExtractorAtom',
        sourceField: 'ultimateEnds',
        targetAtom: 'ultimateEventsAtom',
        targetField: 'ultimates',
        label: 'combines'
      },
      
      // Derived State Dependencies
      {
        sourceAtom: 'matchDataAtom',
        sourceField: 'matches',
        targetAtom: 'playerStatusTimelineAtom',
        targetField: 'timeline',
        label: 'tracks'
      },
      {
        sourceAtom: 'playerEventsAtom',
        sourceField: 'events',
        targetAtom: 'playerStatusTimelineAtom',
        targetField: 'timeline',
        label: 'builds'
      },
      {
        sourceAtom: 'playerInteractionEventsAtom',
        sourceField: 'interactions',
        targetAtom: 'teamfightsAtom',
        targetField: 'teamfights',
        label: 'identifies'
      },
      {
        sourceAtom: 'killExtractorAtom',
        sourceField: 'kills',
        targetAtom: 'playerLivesAtom',
        targetField: 'lives',
        label: 'tracks'
      },
      {
        sourceAtom: 'heroSpawnExtractorAtom',
        sourceField: 'heroSpawns',
        targetAtom: 'playerLivesAtom',
        targetField: 'lives',
        label: 'tracks'
      },
      {
        sourceAtom: 'heroSwapExtractorAtom',
        sourceField: 'heroSwaps',
        targetAtom: 'playerLivesAtom',
        targetField: 'lives',
        label: 'tracks'
      },
      
      // Derived Stats Dependencies
      {
        sourceAtom: 'matchDataAtom',
        sourceField: 'matches',
        targetAtom: 'killMatrixAtom',
        targetField: 'killMatrix',
        label: 'calculates'
      },
      {
        sourceAtom: 'playerInteractionEventsAtom',
        sourceField: 'interactions',
        targetAtom: 'killMatrixAtom',
        targetField: 'killMatrix',
        label: 'analyzes'
      },
      {
        sourceAtom: 'teamfightsAtom',
        sourceField: 'teamfights',
        targetAtom: 'firstKillImpactAtom',
        targetField: 'firstKillImpact',
        label: 'analyzes'
      },
      {
        sourceAtom: 'ultimateEventsAtom',
        sourceField: 'ultimates',
        targetAtom: 'ultimateImpactAtom',
        targetField: 'ultimateImpact',
        label: 'calculates'
      },
      {
        sourceAtom: 'teamfightsAtom',
        sourceField: 'teamfights',
        targetAtom: 'ultimateImpactAtom',
        targetField: 'ultimateImpact',
        label: 'contextualizes'
      },
      {
        sourceAtom: 'teamfightsAtom',
        sourceField: 'teamfights',
        targetAtom: 'teamfightParticipationAtom',
        targetField: 'participation',
        label: 'calculates'
      },
      {
        sourceAtom: 'playerInteractionEventsAtom',
        sourceField: 'interactions',
        targetAtom: 'teamfightParticipationAtom',
        targetField: 'participation',
        label: 'analyzes'
      },
      
      // Metrics Dependencies
      {
        sourceAtom: 'matchDataAtom',
        sourceField: 'matches',
        targetAtom: 'playerMetricsAtoms',
        targetField: 'metrics',
        label: 'calculates'
      },
      {
        sourceAtom: 'playerInteractionEventsAtom',
        sourceField: 'interactions',
        targetAtom: 'playerMetricsAtoms',
        targetField: 'metrics',
        label: 'enhances'
      },
      {
        sourceAtom: 'playerStatusTimelineAtom',
        sourceField: 'timeline',
        targetAtom: 'heroPlaytimeAtom',
        targetField: 'playtime',
        label: 'calculates'
      },
      {
        sourceAtom: 'matchDataAtom',
        sourceField: 'matches',
        targetAtom: 'teamStatsAtom',
        targetField: 'stats',
        label: 'calculates'
      },
      {
        sourceAtom: 'playerMetricsAtoms',
        sourceField: 'metrics',
        targetAtom: 'teamStatsAtom',
        targetField: 'stats',
        label: 'aggregates'
      }
    ]
  };
};
