import { useAuth } from "react-oidc-context";
import PrimaryButton from "@components/PrimaryButton";
import { Play, BarChart3, Upload, Check, X, Target, Users } from "lucide-react";

const LandingPage = () => {
  const auth = useAuth();

  const handleSignIn = () => {
    auth.signinRedirect();
  };

  
  return (
    // 1. Top nav with logo, link to product / pricing / FAQ sections, buttons for view demo / login 
    // 2. Hero section with textured background, gradient orange to purple
    // 2.1 Headline: "Get serious about your scrims"
    // 2.2 Subheading: "Take your team to the next level with actionable insights and analytics with Scrimsight"
    // 2.3 Primary CTA button: "Get Started with Discord"
    // 2.4 Secondary CTA button: "Explore Demo"
    // 3. Features section with 3 cards:
    // 3.1 Easy integration - Load your Scrimtime logs and get instant insights
    // 3.2 Actionable insights - Find the structure behind the chaos of scrims by reviewing matches and exploring player and team performance
    // 3.3 Secure and private - Your data is processed locally and never leaves your device, ensuring your strategies remain confidential
    // 4. Feature demos in a list with title, description, and (placeholder) demo:
    // 4.1 Match timeline - Complement your in-game replays with detailed timelines showing teamfights, ultimate economy, and kill breakdowns
    // 4.2 Player performance - Analyze individual player stats, including KDA, damage/healing dealt, ultimate efficiency, and hero performance
    // 4.3 Team synergy - Review team compositions, historical trends, and coordination to improve teamwork and strategy
    // 5. Pricing section with 2 cards:
    // 5.1 Casual plan - $0/month, max 5 matches
    // 5.2 Pro plan - $10/month, unlimited matches, advanced analytics, and priority support
    // 6. FAQ section with accordions:
    // 6.1 What is Scrimsight? Scrimsight is a data-driven web application that helps players and teams improve their performance by providing actionable insights and analytics.
    // 6.2 How does it work? Scrimsight integrates with your existing scrim logs generated by Scrimtime, processes the data locally, and provides detailed analytics on player and team performance.
    // 6.3 Is my data secure? Scrimsight processes your data locally and never sends it to external servers, ensuring your strategies and performance data remain confidential.
    // 7. Get started section with a call to action
    // 7.1 Sign in with Discord button
    // 7.2 View demo button
    // 8. Footer with links to Discord and contact information, copyright notice
  );
};

export default LandingPage;
