import { describe, it, expect } from 'vitest';
import { uniquePlayerNamesAtomFn } from '@atoms/uniquePlayerNamesAtom';
import type { PlayerStatType } from '@atoms';

describe('uniquePlayerNamesAtomFn', () => {
  it('should extract unique player names from player stats', () => {
    const mockPlayerStats: PlayerStatType = [
      {
        matchId: 'match1',
        type: 'player_stat',
        matchTime: 150,
        roundNumber: '1',
        playerTeam: 'Team A',
        playerName: 'Player1',
        playerHero: 'Tracer',
        eliminations: 25,
        finalBlows: 20,
        deaths: 5,
        allDamageDealt: 5000,
        barrierDamageDealt: 1000,
        heroDamageDealt: 4000,
        healingDealt: 0,
        healingReceived: 1500,
        selfHealing: 100,
        damageTaken: 3000,
        damageBlocked: 0,
        defensiveAssists: 2,
        offensiveAssists: 8,
        ultimatesEarned: 3,
        ultimatesUsed: 2,
        multikillBest: 3,
        multikills: 5,
        soloKills: 10,
        objectiveKills: 5,
        environmentalKills: 0,
        environmentalDeaths: 1,
        criticalHits: 50,
        criticalHitAccuracy: 0.15,
        scopedAccuracy: 0,
        scopedCriticalHitAccuracy: 0,
        scopedCriticalHitKills: 0,
        shotsFired: 300,
        shotsHit: 180,
        shotsMissed: 120,
        scopedShotsFired: 0,
        scopedShotsHit: 0,
        weaponAccuracy: 0.6,
      },
      {
        matchId: 'match1',
        type: 'player_stat',
        matchTime: 150,
        roundNumber: '1',
        playerTeam: 'Team A',
        playerName: 'Player2',
        playerHero: 'Ana',
        eliminations: 15,
        finalBlows: 10,
        deaths: 3,
        allDamageDealt: 3000,
        barrierDamageDealt: 500,
        heroDamageDealt: 2500,
        healingDealt: 8000,
        healingReceived: 1000,
        selfHealing: 200,
        damageTaken: 2000,
        damageBlocked: 0,
        defensiveAssists: 5,
        offensiveAssists: 3,
        ultimatesEarned: 4,
        ultimatesUsed: 3,
        multikillBest: 2,
        multikills: 2,
        soloKills: 5,
        objectiveKills: 3,
        environmentalKills: 0,
        environmentalDeaths: 0,
        criticalHits: 25,
        criticalHitAccuracy: 0.2,
        scopedAccuracy: 0.7,
        scopedCriticalHitAccuracy: 0.3,
        scopedCriticalHitKills: 8,
        shotsFired: 200,
        shotsHit: 140,
        shotsMissed: 60,
        scopedShotsFired: 50,
        scopedShotsHit: 35,
        weaponAccuracy: 0.7,
      },
      {
        matchId: 'match2',
        type: 'player_stat',
        matchTime: 200,
        roundNumber: '2',
        playerTeam: 'Team B',
        playerName: 'Player1',
        playerHero: 'Genji',
        eliminations: 30,
        finalBlows: 25,
        deaths: 4,
        allDamageDealt: 6000,
        barrierDamageDealt: 800,
        heroDamageDealt: 5200,
        healingDealt: 0,
        healingReceived: 2000,
        selfHealing: 150,
        damageTaken: 3500,
        damageBlocked: 0,
        defensiveAssists: 1,
        offensiveAssists: 12,
        ultimatesEarned: 4,
        ultimatesUsed: 3,
        multikillBest: 4,
        multikills: 6,
        soloKills: 15,
        objectiveKills: 8,
        environmentalKills: 1,
        environmentalDeaths: 0,
        criticalHits: 80,
        criticalHitAccuracy: 0.25,
        scopedAccuracy: 0,
        scopedCriticalHitAccuracy: 0,
        scopedCriticalHitKills: 0,
        shotsFired: 400,
        shotsHit: 250,
        shotsMissed: 150,
        scopedShotsFired: 0,
        scopedShotsHit: 0,
        weaponAccuracy: 0.625,
      }
    ];

    const result = uniquePlayerNamesAtomFn(mockPlayerStats);

    expect(result).toEqual(['Player1', 'Player2']);
    expect(result).toHaveLength(2);
  });

  it('should return empty array when no player stats provided', () => {
    const result = uniquePlayerNamesAtomFn([]);

    expect(result).toEqual([]);
    expect(result).toHaveLength(0);
  });

  it('should handle single player stat', () => {
    const mockPlayerStats: PlayerStatType = [
      {
        matchId: 'match1',
        type: 'player_stat',
        matchTime: 150,
        roundNumber: '1',
        playerTeam: 'Team A',
        playerName: 'SoloPlayer',
        playerHero: 'Mercy',
        eliminations: 5,
        finalBlows: 3,
        deaths: 2,
        allDamageDealt: 1000,
        barrierDamageDealt: 200,
        heroDamageDealt: 800,
        healingDealt: 6000,
        healingReceived: 800,
        selfHealing: 300,
        damageTaken: 1500,
        damageBlocked: 0,
        defensiveAssists: 8,
        offensiveAssists: 2,
        ultimatesEarned: 5,
        ultimatesUsed: 4,
        multikillBest: 1,
        multikills: 1,
        soloKills: 2,
        objectiveKills: 1,
        environmentalKills: 0,
        environmentalDeaths: 0,
        criticalHits: 10,
        criticalHitAccuracy: 0.3,
        scopedAccuracy: 0.8,
        scopedCriticalHitAccuracy: 0.4,
        scopedCriticalHitKills: 3,
        shotsFired: 100,
        shotsHit: 80,
        shotsMissed: 20,
        scopedShotsFired: 30,
        scopedShotsHit: 24,
        weaponAccuracy: 0.8,
      }
    ];

    const result = uniquePlayerNamesAtomFn(mockPlayerStats);

    expect(result).toEqual(['SoloPlayer']);
    expect(result).toHaveLength(1);
  });

  it('should handle multiple stats from same player', () => {
    const mockPlayerStats: PlayerStatType = [
      {
        matchId: 'match1',
        type: 'player_stat',
        matchTime: 150,
        roundNumber: '1',
        playerTeam: 'Team A',
        playerName: 'ConsistentPlayer',
        playerHero: 'Soldier: 76',
        eliminations: 20,
        finalBlows: 18,
        deaths: 6,
        allDamageDealt: 8000,
        barrierDamageDealt: 2000,
        heroDamageDealt: 6000,
        healingDealt: 0,
        healingReceived: 1200,
        selfHealing: 200,
        damageTaken: 4000,
        damageBlocked: 0,
        defensiveAssists: 3,
        offensiveAssists: 10,
        ultimatesEarned: 3,
        ultimatesUsed: 2,
        multikillBest: 3,
        multikills: 4,
        soloKills: 8,
        objectiveKills: 6,
        environmentalKills: 0,
        environmentalDeaths: 1,
        criticalHits: 60,
        criticalHitAccuracy: 0.2,
        scopedAccuracy: 0,
        scopedCriticalHitAccuracy: 0,
        scopedCriticalHitKills: 0,
        shotsFired: 350,
        shotsHit: 220,
        shotsMissed: 130,
        scopedShotsFired: 0,
        scopedShotsHit: 0,
        weaponAccuracy: 0.63,
      },
      {
        matchId: 'match2',
        type: 'player_stat',
        matchTime: 300,
        roundNumber: '2',
        playerTeam: 'Team A',
        playerName: 'ConsistentPlayer',
        playerHero: 'Soldier: 76',
        eliminations: 22,
        finalBlows: 19,
        deaths: 5,
        allDamageDealt: 8500,
        barrierDamageDealt: 2200,
        heroDamageDealt: 6300,
        healingDealt: 0,
        healingReceived: 1100,
        selfHealing: 250,
        damageTaken: 3800,
        damageBlocked: 0,
        defensiveAssists: 2,
        offensiveAssists: 12,
        ultimatesEarned: 4,
        ultimatesUsed: 3,
        multikillBest: 4,
        multikills: 5,
        soloKills: 9,
        objectiveKills: 7,
        environmentalKills: 1,
        environmentalDeaths: 0,
        criticalHits: 65,
        criticalHitAccuracy: 0.22,
        scopedAccuracy: 0,
        scopedCriticalHitAccuracy: 0,
        scopedCriticalHitKills: 0,
        shotsFired: 380,
        shotsHit: 240,
        shotsMissed: 140,
        scopedShotsFired: 0,
        scopedShotsHit: 0,
        weaponAccuracy: 0.63,
      }
    ];

    const result = uniquePlayerNamesAtomFn(mockPlayerStats);

    expect(result).toEqual(['ConsistentPlayer']);
    expect(result).toHaveLength(1);
  });
});