flowchart
    subgraph src["src"]
        src/App.tsx["App.tsx"]
        src/index.tsx["index.tsx"]
        subgraph src/lib["/lib"]
            src/lib/base64.ts["base64.ts"]
            src/lib/color.ts["color.ts"]
            src/lib/date.ts["date.ts"]
            src/lib/string.ts["string.ts"]
            src/lib/time.ts["time.ts"]
            src/lib/format.ts["format.ts"]
            src/lib/hero.ts["hero.ts"]
            src/lib/index.ts["index.ts"]
            src/lib/scrimtime.ts["scrimtime.ts"]
            src/lib/eventExtractionUtils.ts["eventExtractionUtils.ts"]
            src/lib/metricUtils.ts["metricUtils.ts"]
            src/lib/playerMetricsUtils.ts["playerMetricsUtils.ts"]
            src/lib/playerComparison.ts["playerComparison.ts"]
            src/lib/killMatrixUtils.ts["killMatrixUtils.ts"]
            src/lib/useAtomData.ts["useAtomData.ts"]
            src/lib/useMetricsTableColumns.ts["useMetricsTableColumns.ts"]
            src/lib/atomDataService.ts["atomDataService.ts"]
            src/lib/schemaVisualizer.ts["schemaVisualizer.ts"]
            src/lib/metricExplorerStyles.ts["metricExplorerStyles.ts"]
            src/lib/dagre.ts["dagre.ts"]
            src/lib/playerEvents.ts["playerEvents.ts"]
            src/lib/types.ts["types.ts"]
        end
        subgraph src/atoms["/atoms"]
            src/atoms/teamPlayers.ts["teamPlayers.ts"]
            src/atoms/index.ts["index.ts"]
            src/atoms/sampleDataEnabled.ts["sampleDataEnabled.ts"]
            src/atoms/sampleData.ts["sampleData.ts"]
            src/atoms/logFileInputAtom.ts["logFileInputAtom.ts"]
            src/atoms/logFileLoaderAtom.ts["logFileLoaderAtom.ts"]
            src/atoms/logFileParserAtom.ts["logFileParserAtom.ts"]
            src/atoms/averageMetricPerHeroAtom.ts["averageMetricPerHeroAtom.ts"]
            src/atoms/averageMetricPerMapAtom.ts["averageMetricPerMapAtom.ts"]
            src/atoms/averageMetricPerRoleAtom.ts["averageMetricPerRoleAtom.ts"]
            src/atoms/firstKillImpactAtom.ts["firstKillImpactAtom.ts"]
            src/atoms/teamfightsAtom.ts["teamfightsAtom.ts"]
            src/atoms/playerInteractionEventsAtom.ts["playerInteractionEventsAtom.ts"]
            src/atoms/ultimateEventsAtom.ts["ultimateEventsAtom.ts"]
            src/atoms/uniqueHeroNamesAtom.ts["uniqueHeroNamesAtom.ts"]
            src/atoms/playerStatsBaseAtom.ts["playerStatsBaseAtom.ts"]
            src/atoms/uniqueCategoryValuesAtom.ts["uniqueCategoryValuesAtom.ts"]
            src/atoms/ability1Used.ts["ability1Used.ts"]
            src/atoms/ability2Used.ts["ability2Used.ts"]
            src/atoms/damage.ts["damage.ts"]
            src/atoms/defensiveAssist.ts["defensiveAssist.ts"]
            src/atoms/dvaDemech.ts["dvaDemech.ts"]
            src/atoms/dvaRemech.ts["dvaRemech.ts"]
            src/atoms/healing.ts["healing.ts"]
            src/atoms/heroSpawn.ts["heroSpawn.ts"]
            src/atoms/heroSwap.ts["heroSwap.ts"]
            src/atoms/kill.ts["kill.ts"]
            src/atoms/matchEnd.ts["matchEnd.ts"]
            src/atoms/matchStart.ts["matchStart.ts"]
            src/atoms/mercyRez.ts["mercyRez.ts"]
            src/atoms/offensiveAssist.ts["offensiveAssist.ts"]
            src/atoms/playerStat.ts["playerStat.ts"]
            src/atoms/roundEnd.ts["roundEnd.ts"]
            src/atoms/roundStart.ts["roundStart.ts"]
            src/atoms/setupComplete.ts["setupComplete.ts"]
            src/atoms/ultimateCharged.ts["ultimateCharged.ts"]
            src/atoms/ultimateEnd.ts["ultimateEnd.ts"]
            src/atoms/ultimateStart.ts["ultimateStart.ts"]
            src/atoms/teamfightParticipationAtom.ts["teamfightParticipationAtom.ts"]
            src/atoms/uniquePlayerNamesAtom.ts["uniquePlayerNamesAtom.ts"]
            src/atoms/roundTimesAtom.ts["roundTimesAtom.ts"]
            src/atoms/playerStatusTimelineAtom.ts["playerStatusTimelineAtom.ts"]
            src/atoms/playerEventsAtom.ts["playerEventsAtom.ts"]
            src/atoms/playerFirstKillDeathRateAtom.ts["playerFirstKillDeathRateAtom.ts"]
            src/atoms/matchDataAtom.ts["matchDataAtom.ts"]
            src/atoms/uniqueMapNamesAtom.ts["uniqueMapNamesAtom.ts"]
            src/atoms/scrimAtom.ts["scrimAtom.ts"]
            src/atoms/teamStatsAtom.ts["teamStatsAtom.ts"]
            src/atoms/mapTimesAtom.ts["mapTimesAtom.ts"]
            src/atoms/matchExtractorAtom.ts["matchExtractorAtom.ts"]
            src/atoms/heroPlaytimeAtom.ts["heroPlaytimeAtom.ts"]
            src/atoms/teamNamesAtom.ts["teamNamesAtom.ts"]
            src/atoms/killMatrixAtom.ts["killMatrixAtom.ts"]
            src/atoms/playerLivesAtom.ts["playerLivesAtom.ts"]
            src/atoms/groupedEventsAtom.ts["groupedEventsAtom.ts"]
            src/atoms/listSummaryAtoms.ts["listSummaryAtoms.ts"]
            src/atoms/detailedTeamCompositionsAtom.ts["detailedTeamCompositionsAtom.ts"]
            src/atoms/teamMapTypeStatsAtom.ts["teamMapTypeStatsAtom.ts"]
            src/atoms/contextualStatAtoms.ts["contextualStatAtoms.ts"]
            src/atoms/killMatrix.ts["killMatrix.ts"]
            src/atoms/playerComparison.ts["playerComparison.ts"]
            src/atoms/playerComparisonAtomFamily.ts["playerComparisonAtomFamily.ts"]
            src/atoms/playerListSummary.ts["playerListSummary.ts"]
            src/atoms/playerMatchHistoryAtom.ts["playerMatchHistoryAtom.ts"]
            src/atoms/playerStatExpandedAtom.ts["playerStatExpandedAtom.ts"]
            src/atoms/segmentStatsAtomFamily.ts["segmentStatsAtomFamily.ts"]
            src/atoms/teamCompositionsAtom.ts["teamCompositionsAtom.ts"]
            src/atoms/ultimateImpactAtom.ts["ultimateImpactAtom.ts"]
            src/atoms/uniqueGameModesAtom.ts["uniqueGameModesAtom.ts"]
        end
        subgraph src/components["/components"]
            src/components/CardBase.tsx["CardBase.tsx"]
            src/components/CompositionCard.tsx["CompositionCard.tsx"]
            src/components/Container.tsx["Container.tsx"]
            src/components/ErrorMessage.tsx["ErrorMessage.tsx"]
            src/components/HeatmapGrid.tsx["HeatmapGrid.tsx"]
            src/components/IconAndText.tsx["IconAndText.tsx"]
            src/components/IconAutocomplete.tsx["IconAutocomplete.tsx"]
            src/components/KillsTable.tsx["KillsTable.tsx"]
            src/components/index.ts["index.ts"]
            src/components/Layout.tsx["Layout.tsx"]
            src/components/LoadFilesButton.tsx["LoadFilesButton.tsx"]
            src/components/MatchCard.tsx["MatchCard.tsx"]
            src/components/Navigation.tsx["Navigation.tsx"]
            src/components/PlayerCard.tsx["PlayerCard.tsx"]
            src/components/ProgressBar.tsx["ProgressBar.tsx"]
            src/components/RoleCheckbox.tsx["RoleCheckbox.tsx"]
            src/components/RoleControl.tsx["RoleControl.tsx"]
            src/components/ScrimCard.tsx["ScrimCard.tsx"]
            src/components/StatCard.tsx["StatCard.tsx"]
            src/components/SubPageNavigation.tsx["SubPageNavigation.tsx"]
            src/components/TeamCard.tsx["TeamCard.tsx"]
            src/components/TimeRangeSlider.tsx["TimeRangeSlider.tsx"]
            src/components/TimeSegmentDisplay.tsx["TimeSegmentDisplay.tsx"]
            src/components/Timeline.tsx["Timeline.tsx"]
            src/components/TimelineButton.tsx["TimelineButton.tsx"]
            src/components/TimelineContext.tsx["TimelineContext.tsx"]
            src/components/TimelineControls.tsx["TimelineControls.tsx"]
            src/components/TimelineDisplay.tsx["TimelineDisplay.tsx"]
            src/components/TimelineEvents.tsx["TimelineEvents.tsx"]
            src/components/TimelineTable.tsx["TimelineTable.tsx"]
            src/components/AllPlayerComparison.tsx["AllPlayerComparison.tsx"]
            src/components/AtomNode.tsx["AtomNode.tsx"]
            src/components/EdgeLabel.tsx["EdgeLabel.tsx"]
            src/components/LayerSelector.tsx["LayerSelector.tsx"]
            src/components/MatchScoreCard.tsx["MatchScoreCard.tsx"]
            src/components/MetricsChart.tsx["MetricsChart.tsx"]
            src/components/MetricsControls.tsx["MetricsControls.tsx"]
            src/components/MetricsDataTable.tsx["MetricsDataTable.tsx"]
            src/components/PlayerHeroes.tsx["PlayerHeroes.tsx"]
            src/components/PlayerList.tsx["PlayerList.tsx"]
            src/components/PlayerMatches.tsx["PlayerMatches.tsx"]
            src/components/PlayerOverview.tsx["PlayerOverview.tsx"]
            src/components/PlayerStatsCard.tsx["PlayerStatsCard.tsx"]
            src/components/PlayerStatsComparison.tsx["PlayerStatsComparison.tsx"]
            src/components/PlayersHeroes.tsx["PlayersHeroes.tsx"]
            src/components/PlayersOverview.tsx["PlayersOverview.tsx"]
            src/components/PlayersPerformance.tsx["PlayersPerformance.tsx"]
            src/components/ScrimsMatchCard.tsx["ScrimsMatchCard.tsx"]
            src/components/SingleStatPlayerComparison.tsx["SingleStatPlayerComparison.tsx"]
            src/components/TeamCompositions.tsx["TeamCompositions.tsx"]
            src/components/TeamMatches.tsx["TeamMatches.tsx"]
            src/components/TeamOverview.tsx["TeamOverview.tsx"]
            src/components/TeamPlayers.tsx["TeamPlayers.tsx"]
            src/components/TeamStatsComparison.tsx["TeamStatsComparison.tsx"]
            src/components/TeamsFilter.tsx["TeamsFilter.tsx"]
            src/components/TeamsList.tsx["TeamsList.tsx"]
            src/components/TeamsSummaryStats.tsx["TeamsSummaryStats.tsx"]
            src/components/TeamsVisualization.tsx["TeamsVisualization.tsx"]
            src/components/TopPlayersList.tsx["TopPlayersList.tsx"]
            src/components/ZeroState.tsx["ZeroState.tsx"]
        end
        subgraph src/icons["/icons"]
            src/icons/BeamsAuraIcon.tsx["BeamsAuraIcon.tsx"]
            src/icons/GhostAllyIcon.tsx["GhostAllyIcon.tsx"]
            src/icons/GrimReaperIcon.tsx["GrimReaperIcon.tsx"]
            src/icons/HealingIcon.tsx["HealingIcon.tsx"]
            src/icons/MacheteIcon.tsx["MacheteIcon.tsx"]
            src/icons/RoleIcon.tsx["RoleIcon.tsx"]
            src/icons/RoleSvgIcon.tsx["RoleSvgIcon.tsx"]
            src/icons/UpCardIcon.tsx["UpCardIcon.tsx"]
            src/icons/index.ts["index.ts"]
        end
        subgraph src/pages["/pages"]
            src/pages/AddFilesPage.tsx["AddFilesPage.tsx"]
            src/pages/CallbackPage.tsx["CallbackPage.tsx"]
            src/pages/HomePage.tsx["HomePage.tsx"]
            src/pages/MatchOverviewPage.tsx["MatchOverviewPage.tsx"]
            src/pages/MatchPage.tsx["MatchPage.tsx"]
            src/pages/MatchPlayersPage.tsx["MatchPlayersPage.tsx"]
            src/pages/MatchStatComparisonPage.tsx["MatchStatComparisonPage.tsx"]
            src/pages/TimelinePage.tsx["TimelinePage.tsx"]
            src/pages/MetricsExplorerPage.tsx["MetricsExplorerPage.tsx"]
            src/pages/PlayerPage.tsx["PlayerPage.tsx"]
            src/pages/PlayersPage.tsx["PlayersPage.tsx"]
            src/pages/SchemaVisualizerPage.tsx["SchemaVisualizerPage.tsx"]
            src/pages/ScrimPage.tsx["ScrimPage.tsx"]
            src/pages/ScrimsPage.tsx["ScrimsPage.tsx"]
            src/pages/TeamPage.tsx["TeamPage.tsx"]
            src/pages/TeamsPage.tsx["TeamsPage.tsx"]
            src/pages/index.tsx["index.tsx"]
        end
    end
    src/lib/hero.ts-->src/lib/index.ts
    src/lib/scrimtime.ts-->src/lib/index.ts
    src/lib/playerMetricsUtils.ts-->src/lib/index.ts
    src/lib/useAtomData.ts-->src/lib/index.ts
    src/lib/useMetricsTableColumns.ts-->src/lib/index.ts
    src/lib/atomDataService.ts-->src/lib/index.ts
    src/lib/metricExplorerStyles.ts-->src/lib/index.ts
    src/atoms/teamPlayers.ts-->src/atoms/index.ts
    src/atoms/sampleDataEnabled.ts-->src/atoms/index.ts
    src/atoms/sampleData.ts-->src/atoms/index.ts
    src/atoms/logFileInputAtom.ts-->src/atoms/index.ts
    src/atoms/logFileLoaderAtom.ts-->src/lib/index.ts
    src/atoms/logFileLoaderAtom.ts-->src/atoms/index.ts
    src/atoms/logFileParserAtom.ts-->src/lib/index.ts
    src/atoms/logFileParserAtom.ts-->src/atoms/index.ts
    src/atoms/averageMetricPerHeroAtom.ts-->src/atoms/index.ts
    src/atoms/averageMetricPerHeroAtom.ts-->src/lib/index.ts
    src/atoms/averageMetricPerMapAtom.ts-->src/lib/index.ts
    src/atoms/averageMetricPerMapAtom.ts-->src/atoms/index.ts
    src/atoms/averageMetricPerRoleAtom.ts-->src/lib/index.ts
    src/atoms/averageMetricPerRoleAtom.ts-->src/atoms/index.ts
    src/atoms/firstKillImpactAtom.ts-->src/atoms/index.ts
    src/atoms/teamfightsAtom.ts-->src/atoms/index.ts
    src/atoms/playerInteractionEventsAtom.ts-->src/atoms/index.ts
    src/atoms/ultimateEventsAtom.ts-->src/atoms/index.ts
    src/atoms/uniqueHeroNamesAtom.ts-->src/atoms/index.ts
    src/atoms/uniqueHeroNamesAtom.ts-->src/lib/index.ts
    src/atoms/playerStatsBaseAtom.ts-->src/atoms/index.ts
    src/atoms/playerStatsBaseAtom.ts-->src/lib/index.ts
    src/atoms/uniqueCategoryValuesAtom.ts-->src/lib/index.ts
    src/atoms/uniqueCategoryValuesAtom.ts-->src/atoms/index.ts
    src/atoms/ability1Used.ts-->src/atoms/index.ts
    src/atoms/ability1Used.ts-->src/lib/index.ts
    src/atoms/ability2Used.ts-->src/atoms/index.ts
    src/atoms/ability2Used.ts-->src/lib/index.ts
    src/atoms/damage.ts-->src/atoms/index.ts
    src/atoms/damage.ts-->src/lib/index.ts
    src/atoms/defensiveAssist.ts-->src/atoms/index.ts
    src/atoms/defensiveAssist.ts-->src/lib/index.ts
    src/atoms/dvaDemech.ts-->src/atoms/index.ts
    src/atoms/dvaDemech.ts-->src/lib/index.ts
    src/atoms/dvaRemech.ts-->src/atoms/index.ts
    src/atoms/dvaRemech.ts-->src/lib/index.ts
    src/atoms/healing.ts-->src/atoms/index.ts
    src/atoms/healing.ts-->src/lib/index.ts
    src/atoms/heroSpawn.ts-->src/atoms/index.ts
    src/atoms/heroSpawn.ts-->src/lib/index.ts
    src/atoms/heroSwap.ts-->src/atoms/index.ts
    src/atoms/heroSwap.ts-->src/lib/index.ts
    src/atoms/kill.ts-->src/atoms/index.ts
    src/atoms/kill.ts-->src/lib/index.ts
    src/atoms/matchEnd.ts-->src/atoms/index.ts
    src/atoms/matchEnd.ts-->src/lib/index.ts
    src/atoms/matchStart.ts-->src/atoms/index.ts
    src/atoms/matchStart.ts-->src/lib/index.ts
    src/atoms/mercyRez.ts-->src/atoms/index.ts
    src/atoms/mercyRez.ts-->src/lib/index.ts
    src/atoms/offensiveAssist.ts-->src/atoms/index.ts
    src/atoms/offensiveAssist.ts-->src/lib/index.ts
    src/atoms/playerStat.ts-->src/atoms/index.ts
    src/atoms/playerStat.ts-->src/lib/index.ts
    src/atoms/roundEnd.ts-->src/atoms/index.ts
    src/atoms/roundEnd.ts-->src/lib/index.ts
    src/atoms/roundStart.ts-->src/atoms/index.ts
    src/atoms/roundStart.ts-->src/lib/index.ts
    src/atoms/setupComplete.ts-->src/atoms/index.ts
    src/atoms/setupComplete.ts-->src/lib/index.ts
    src/atoms/ultimateCharged.ts-->src/atoms/index.ts
    src/atoms/ultimateCharged.ts-->src/lib/index.ts
    src/atoms/ultimateEnd.ts-->src/atoms/index.ts
    src/atoms/ultimateEnd.ts-->src/lib/index.ts
    src/atoms/ultimateStart.ts-->src/atoms/index.ts
    src/atoms/ultimateStart.ts-->src/lib/index.ts
    src/atoms/teamfightParticipationAtom.ts-->src/atoms/index.ts
    src/atoms/uniquePlayerNamesAtom.ts-->src/atoms/index.ts
    src/atoms/roundTimesAtom.ts-->src/atoms/index.ts
    src/atoms/playerStatusTimelineAtom.ts-->src/atoms/index.ts
    src/atoms/playerEventsAtom.ts-->src/atoms/index.ts
    src/atoms/playerFirstKillDeathRateAtom.ts-->src/atoms/index.ts
    src/atoms/matchDataAtom.ts-->src/atoms/index.ts
    src/atoms/uniqueMapNamesAtom.ts-->src/atoms/index.ts
    src/atoms/scrimAtom.ts-->src/atoms/index.ts
    src/atoms/teamStatsAtom.ts-->src/atoms/index.ts
    src/atoms/mapTimesAtom.ts-->src/atoms/index.ts
    src/atoms/matchExtractorAtom.ts-->src/atoms/index.ts
    src/atoms/heroPlaytimeAtom.ts-->src/atoms/index.ts
    src/atoms/teamNamesAtom.ts-->src/atoms/index.ts
    src/atoms/killMatrixAtom.ts-->src/atoms/index.ts
    src/atoms/playerLivesAtom.ts-->src/atoms/index.ts
    src/atoms/groupedEventsAtom.ts-->src/atoms/index.ts
    src/atoms/listSummaryAtoms.ts-->src/atoms/index.ts
    src/atoms/listSummaryAtoms.ts-->src/lib/index.ts
    src/atoms/detailedTeamCompositionsAtom.ts-->src/atoms/index.ts
    src/atoms/teamMapTypeStatsAtom.ts-->src/atoms/index.ts
    src/atoms/contextualStatAtoms.ts-->src/atoms/index.ts
    src/atoms/contextualStatAtoms.ts-->src/lib/index.ts
    src/atoms/index.ts-->src/lib/index.ts
    src/atoms/index.ts-->src/atoms/teamPlayers.ts
    src/atoms/index.ts-->src/atoms/sampleDataEnabled.ts
    src/atoms/index.ts-->src/atoms/sampleData.ts
    src/atoms/index.ts-->src/atoms/logFileInputAtom.ts
    src/atoms/index.ts-->src/atoms/logFileLoaderAtom.ts
    src/atoms/index.ts-->src/atoms/logFileParserAtom.ts
    src/atoms/index.ts-->src/atoms/averageMetricPerHeroAtom.ts
    src/atoms/index.ts-->src/atoms/averageMetricPerMapAtom.ts
    src/atoms/index.ts-->src/atoms/averageMetricPerRoleAtom.ts
    src/atoms/index.ts-->src/atoms/firstKillImpactAtom.ts
    src/atoms/index.ts-->src/atoms/teamfightsAtom.ts
    src/atoms/index.ts-->src/atoms/playerInteractionEventsAtom.ts
    src/atoms/index.ts-->src/atoms/ultimateEventsAtom.ts
    src/atoms/index.ts-->src/atoms/uniqueHeroNamesAtom.ts
    src/atoms/index.ts-->src/atoms/playerStatsBaseAtom.ts
    src/atoms/index.ts-->src/atoms/uniqueCategoryValuesAtom.ts
    src/atoms/index.ts-->src/atoms/ability1Used.ts
    src/atoms/index.ts-->src/atoms/ability2Used.ts
    src/atoms/index.ts-->src/atoms/damage.ts
    src/atoms/index.ts-->src/atoms/defensiveAssist.ts
    src/atoms/index.ts-->src/atoms/dvaDemech.ts
    src/atoms/index.ts-->src/atoms/dvaRemech.ts
    src/atoms/index.ts-->src/atoms/healing.ts
    src/atoms/index.ts-->src/atoms/heroSpawn.ts
    src/atoms/index.ts-->src/atoms/heroSwap.ts
    src/atoms/index.ts-->src/atoms/kill.ts
    src/atoms/index.ts-->src/atoms/matchEnd.ts
    src/atoms/index.ts-->src/atoms/matchStart.ts
    src/atoms/index.ts-->src/atoms/mercyRez.ts
    src/atoms/index.ts-->src/atoms/offensiveAssist.ts
    src/atoms/index.ts-->src/atoms/playerStat.ts
    src/atoms/index.ts-->src/atoms/roundEnd.ts
    src/atoms/index.ts-->src/atoms/roundStart.ts
    src/atoms/index.ts-->src/atoms/setupComplete.ts
    src/atoms/index.ts-->src/atoms/ultimateCharged.ts
    src/atoms/index.ts-->src/atoms/ultimateEnd.ts
    src/atoms/index.ts-->src/atoms/ultimateStart.ts
    src/atoms/index.ts-->src/atoms/teamfightParticipationAtom.ts
    src/atoms/index.ts-->src/atoms/uniquePlayerNamesAtom.ts
    src/atoms/index.ts-->src/atoms/roundTimesAtom.ts
    src/atoms/index.ts-->src/atoms/playerStatusTimelineAtom.ts
    src/atoms/index.ts-->src/atoms/playerEventsAtom.ts
    src/atoms/index.ts-->src/atoms/playerFirstKillDeathRateAtom.ts
    src/atoms/index.ts-->src/atoms/matchDataAtom.ts
    src/atoms/index.ts-->src/atoms/uniqueMapNamesAtom.ts
    src/atoms/index.ts-->src/atoms/scrimAtom.ts
    src/atoms/index.ts-->src/atoms/teamStatsAtom.ts
    src/atoms/index.ts-->src/atoms/mapTimesAtom.ts
    src/atoms/index.ts-->src/atoms/matchExtractorAtom.ts
    src/atoms/index.ts-->src/atoms/heroPlaytimeAtom.ts
    src/atoms/index.ts-->src/atoms/teamNamesAtom.ts
    src/atoms/index.ts-->src/atoms/killMatrixAtom.ts
    src/atoms/index.ts-->src/atoms/playerLivesAtom.ts
    src/atoms/index.ts-->src/atoms/groupedEventsAtom.ts
    src/atoms/index.ts-->src/atoms/listSummaryAtoms.ts
    src/atoms/index.ts-->src/atoms/detailedTeamCompositionsAtom.ts
    src/atoms/index.ts-->src/atoms/teamMapTypeStatsAtom.ts
    src/atoms/index.ts-->src/atoms/contextualStatAtoms.ts
    src/lib/index.ts-->src/lib/base64.ts
    src/lib/index.ts-->src/lib/color.ts
    src/lib/index.ts-->src/lib/date.ts
    src/lib/index.ts-->src/lib/string.ts
    src/lib/index.ts-->src/lib/time.ts
    src/lib/index.ts-->src/lib/format.ts
    src/lib/index.ts-->src/lib/hero.ts
    src/lib/index.ts-->src/lib/scrimtime.ts
    src/lib/index.ts-->src/lib/eventExtractionUtils.ts
    src/lib/index.ts-->src/lib/metricUtils.ts
    src/lib/index.ts-->src/lib/playerMetricsUtils.ts
    src/lib/index.ts-->src/lib/playerComparison.ts
    src/lib/index.ts-->src/lib/killMatrixUtils.ts
    src/lib/index.ts-->src/lib/useAtomData.ts
    src/lib/index.ts-->src/lib/useMetricsTableColumns.ts
    src/lib/index.ts-->src/lib/atomDataService.ts
    src/lib/index.ts-->src/lib/schemaVisualizer.ts
    src/lib/index.ts-->src/lib/metricExplorerStyles.ts
    src/lib/index.ts-->src/lib/dagre.ts
    src/lib/index.ts-->src/atoms/index.ts
    src/icons/index.ts-->src/icons/BeamsAuraIcon.tsx
    src/icons/index.ts-->src/icons/GhostAllyIcon.tsx
    src/icons/index.ts-->src/icons/GrimReaperIcon.tsx
    src/icons/index.ts-->src/icons/HealingIcon.tsx
    src/icons/index.ts-->src/icons/MacheteIcon.tsx
    src/icons/index.ts-->src/icons/RoleIcon.tsx
    src/icons/index.ts-->src/icons/RoleSvgIcon.tsx
    src/icons/index.ts-->src/icons/UpCardIcon.tsx
    src/components/CompositionCard.tsx-->src/lib/index.ts
    src/components/CompositionCard.tsx-->src/icons/index.ts
    src/components/KillsTable.tsx-->src/atoms/index.ts
    src/components/KillsTable.tsx-->src/components/index.ts
    src/components/Layout.tsx-->src/components/index.ts
    src/components/Layout.tsx-->src/atoms/index.ts
    src/components/LoadFilesButton.tsx-->src/atoms/index.ts
    src/components/MatchCard.tsx-->src/lib/index.ts
    src/components/MatchCard.tsx-->src/components/index.ts
    src/components/Navigation.tsx-->src/atoms/index.ts
    src/components/Navigation.tsx-->src/lib/index.ts
    src/components/Navigation.tsx-->src/icons/index.ts
    src/components/PlayerCard.tsx-->src/lib/index.ts
    src/components/PlayerCard.tsx-->src/components/index.ts
    src/components/RoleCheckbox.tsx-->src/icons/index.ts
    src/components/RoleCheckbox.tsx-->src/lib/index.ts
    src/components/RoleControl.tsx-->src/lib/index.ts
    src/components/RoleControl.tsx-->src/components/index.ts
    src/components/ScrimCard.tsx-->src/lib/index.ts
    src/components/ScrimCard.tsx-->src/components/index.ts
    src/components/TeamCard.tsx-->src/lib/index.ts
    src/components/TeamCard.tsx-->src/components/index.ts
    src/components/TimeSegmentDisplay.tsx-->src/components/index.ts
    src/components/Timeline.tsx-->src/components/index.ts
    src/components/TimelineContext.tsx-->src/atoms/index.ts
    src/components/TimelineContext.tsx-->src/lib/index.ts
    src/components/TimelineControls.tsx-->src/components/index.ts
    src/components/TimelineControls.tsx-->src/atoms/index.ts
    src/components/TimelineDisplay.tsx-->src/components/index.ts
    src/components/TimelineDisplay.tsx-->src/lib/index.ts
    src/components/TimelineDisplay.tsx-->src/atoms/index.ts
    src/components/TimelineEvents.tsx-->src/components/index.ts
    src/components/TimelineEvents.tsx-->src/lib/index.ts
    src/components/TimelineEvents.tsx-->src/atoms/index.ts
    src/components/TimelineTable.tsx-->src/components/index.ts
    src/components/TimelineTable.tsx-->src/lib/index.ts
    src/components/AllPlayerComparison.tsx-->src/atoms/index.ts
    src/components/AllPlayerComparison.tsx-->src/lib/index.ts
    src/components/AtomNode.tsx-->src/lib/index.ts
    src/components/MetricsChart.tsx-->src/atoms/index.ts
    src/components/MetricsChart.tsx-->src/lib/index.ts
    src/components/MetricsControls.tsx-->src/atoms/index.ts
    src/components/MetricsControls.tsx-->src/lib/index.ts
    src/components/PlayerHeroes.tsx-->src/lib/index.ts
    src/components/PlayerHeroes.tsx-->src/icons/index.ts
    src/components/PlayerList.tsx-->src/components/index.ts
    src/components/PlayerList.tsx-->src/atoms/index.ts
    src/components/PlayerList.tsx-->src/lib/index.ts
    src/components/PlayerMatches.tsx-->src/atoms/index.ts
    src/components/PlayerMatches.tsx-->src/components/index.ts
    src/components/PlayerMatches.tsx-->src/lib/index.ts
    src/components/PlayerOverview.tsx-->src/lib/index.ts
    src/components/PlayerOverview.tsx-->src/atoms/index.ts
    src/components/PlayerOverview.tsx-->src/components/index.ts
    src/components/PlayerStatsCard.tsx-->src/lib/index.ts
    src/components/PlayerStatsCard.tsx-->src/components/index.ts
    src/components/PlayerStatsComparison.tsx-->src/atoms/index.ts
    src/components/PlayerStatsComparison.tsx-->src/lib/index.ts
    src/components/PlayerStatsComparison.tsx-->src/components/index.ts
    src/components/PlayersHeroes.tsx-->src/lib/index.ts
    src/components/PlayersHeroes.tsx-->src/icons/index.ts
    src/components/PlayersOverview.tsx-->src/atoms/index.ts
    src/components/PlayersOverview.tsx-->src/icons/index.ts
    src/components/PlayersOverview.tsx-->src/lib/index.ts
    src/components/PlayersOverview.tsx-->src/components/index.ts
    src/components/PlayersPerformance.tsx-->src/lib/index.ts
    src/components/PlayersPerformance.tsx-->src/icons/index.ts
    src/components/ScrimsMatchCard.tsx-->src/atoms/index.ts
    src/components/ScrimsMatchCard.tsx-->src/lib/index.ts
    src/components/SingleStatPlayerComparison.tsx-->src/atoms/index.ts
    src/components/SingleStatPlayerComparison.tsx-->src/lib/index.ts
    src/components/TeamCompositions.tsx-->src/atoms/index.ts
    src/components/TeamCompositions.tsx-->src/lib/index.ts
    src/components/TeamCompositions.tsx-->src/icons/index.ts
    src/components/TeamCompositions.tsx-->src/components/index.ts
    src/components/TeamMatches.tsx-->src/atoms/index.ts
    src/components/TeamMatches.tsx-->src/lib/index.ts
    src/components/TeamMatches.tsx-->src/components/index.ts
    src/components/TeamOverview.tsx-->src/atoms/index.ts
    src/components/TeamOverview.tsx-->src/components/index.ts
    src/components/TeamOverview.tsx-->src/lib/index.ts
    src/components/TeamPlayers.tsx-->src/atoms/index.ts
    src/components/TeamPlayers.tsx-->src/components/index.ts
    src/components/TeamPlayers.tsx-->src/lib/index.ts
    src/components/TeamStatsComparison.tsx-->src/atoms/index.ts
    src/components/TeamStatsComparison.tsx-->src/lib/index.ts
    src/components/TeamStatsComparison.tsx-->src/components/index.ts
    src/components/TeamsList.tsx-->src/components/index.ts
    src/components/TeamsList.tsx-->src/atoms/index.ts
    src/components/TeamsList.tsx-->src/lib/index.ts
    src/components/TeamsSummaryStats.tsx-->src/components/index.ts
    src/components/TeamsVisualization.tsx-->src/atoms/index.ts
    src/components/TopPlayersList.tsx-->src/lib/index.ts
    src/components/TopPlayersList.tsx-->src/icons/index.ts
    src/components/ZeroState.tsx-->src/lib/index.ts
    src/components/index.ts-->src/components/CardBase.tsx
    src/components/index.ts-->src/components/CompositionCard.tsx
    src/components/index.ts-->src/components/Container.tsx
    src/components/index.ts-->src/components/ErrorMessage.tsx
    src/components/index.ts-->src/components/HeatmapGrid.tsx
    src/components/index.ts-->src/components/IconAndText.tsx
    src/components/index.ts-->src/components/IconAutocomplete.tsx
    src/components/index.ts-->src/components/KillsTable.tsx
    src/components/index.ts-->src/components/Layout.tsx
    src/components/index.ts-->src/components/LoadFilesButton.tsx
    src/components/index.ts-->src/components/MatchCard.tsx
    src/components/index.ts-->src/components/Navigation.tsx
    src/components/index.ts-->src/components/PlayerCard.tsx
    src/components/index.ts-->src/components/ProgressBar.tsx
    src/components/index.ts-->src/components/RoleCheckbox.tsx
    src/components/index.ts-->src/components/RoleControl.tsx
    src/components/index.ts-->src/components/ScrimCard.tsx
    src/components/index.ts-->src/components/StatCard.tsx
    src/components/index.ts-->src/components/SubPageNavigation.tsx
    src/components/index.ts-->src/components/TeamCard.tsx
    src/components/index.ts-->src/components/TimeRangeSlider.tsx
    src/components/index.ts-->src/components/TimeSegmentDisplay.tsx
    src/components/index.ts-->src/components/Timeline.tsx
    src/components/index.ts-->src/components/TimelineButton.tsx
    src/components/index.ts-->src/components/TimelineContext.tsx
    src/components/index.ts-->src/components/TimelineControls.tsx
    src/components/index.ts-->src/components/TimelineDisplay.tsx
    src/components/index.ts-->src/components/TimelineEvents.tsx
    src/components/index.ts-->src/components/TimelineTable.tsx
    src/components/index.ts-->src/icons/index.ts
    src/components/index.ts-->src/components/AllPlayerComparison.tsx
    src/components/index.ts-->src/components/AtomNode.tsx
    src/components/index.ts-->src/components/EdgeLabel.tsx
    src/components/index.ts-->src/components/LayerSelector.tsx
    src/components/index.ts-->src/components/MatchScoreCard.tsx
    src/components/index.ts-->src/components/MetricsChart.tsx
    src/components/index.ts-->src/components/MetricsControls.tsx
    src/components/index.ts-->src/components/MetricsDataTable.tsx
    src/components/index.ts-->src/components/PlayerHeroes.tsx
    src/components/index.ts-->src/components/PlayerList.tsx
    src/components/index.ts-->src/components/PlayerMatches.tsx
    src/components/index.ts-->src/components/PlayerOverview.tsx
    src/components/index.ts-->src/components/PlayerStatsCard.tsx
    src/components/index.ts-->src/components/PlayerStatsComparison.tsx
    src/components/index.ts-->src/components/PlayersHeroes.tsx
    src/components/index.ts-->src/components/PlayersOverview.tsx
    src/components/index.ts-->src/components/PlayersPerformance.tsx
    src/components/index.ts-->src/components/ScrimsMatchCard.tsx
    src/components/index.ts-->src/components/SingleStatPlayerComparison.tsx
    src/components/index.ts-->src/components/TeamCompositions.tsx
    src/components/index.ts-->src/components/TeamMatches.tsx
    src/components/index.ts-->src/components/TeamOverview.tsx
    src/components/index.ts-->src/components/TeamPlayers.tsx
    src/components/index.ts-->src/components/TeamStatsComparison.tsx
    src/components/index.ts-->src/components/TeamsFilter.tsx
    src/components/index.ts-->src/components/TeamsList.tsx
    src/components/index.ts-->src/components/TeamsSummaryStats.tsx
    src/components/index.ts-->src/components/TeamsVisualization.tsx
    src/components/index.ts-->src/components/TopPlayersList.tsx
    src/components/index.ts-->src/components/ZeroState.tsx
    src/pages/AddFilesPage.tsx-->src/lib/index.ts
    src/pages/AddFilesPage.tsx-->src/components/index.ts
    src/pages/HomePage.tsx-->src/lib/index.ts
    src/pages/HomePage.tsx-->src/components/index.ts
    src/pages/MatchOverviewPage.tsx-->src/lib/index.ts
    src/pages/MatchOverviewPage.tsx-->src/components/index.ts
    src/pages/MatchPage.tsx-->src/lib/index.ts
    src/pages/MatchPage.tsx-->src/components/index.ts
    src/pages/MatchPlayersPage.tsx-->src/components/index.ts
    src/pages/MatchStatComparisonPage.tsx-->src/components/index.ts
    src/pages/TimelinePage.tsx-->src/components/index.ts
    src/pages/MetricsExplorerPage.tsx-->src/components/index.ts
    src/pages/MetricsExplorerPage.tsx-->src/lib/index.ts
    src/pages/PlayerPage.tsx-->src/lib/index.ts
    src/pages/PlayerPage.tsx-->src/components/index.ts
    src/pages/PlayersPage.tsx-->src/lib/index.ts
    src/pages/PlayersPage.tsx-->src/components/index.ts
    src/pages/SchemaVisualizerPage.tsx-->src/components/index.ts
    src/pages/SchemaVisualizerPage.tsx-->src/lib/index.ts
    src/pages/ScrimPage.tsx-->src/lib/index.ts
    src/pages/ScrimPage.tsx-->src/components/index.ts
    src/pages/ScrimsPage.tsx-->src/lib/index.ts
    src/pages/ScrimsPage.tsx-->src/components/index.ts
    src/pages/TeamPage.tsx-->src/lib/index.ts
    src/pages/TeamPage.tsx-->src/components/index.ts
    src/pages/TeamsPage.tsx-->src/lib/index.ts
    src/pages/TeamsPage.tsx-->src/components/index.ts
    src/pages/index.tsx-->src/pages/AddFilesPage.tsx
    src/pages/index.tsx-->src/pages/CallbackPage.tsx
    src/pages/index.tsx-->src/pages/HomePage.tsx
    src/pages/index.tsx-->src/pages/MatchOverviewPage.tsx
    src/pages/index.tsx-->src/pages/MatchPage.tsx
    src/pages/index.tsx-->src/pages/MatchPlayersPage.tsx
    src/pages/index.tsx-->src/pages/MatchStatComparisonPage.tsx
    src/pages/index.tsx-->src/pages/TimelinePage.tsx
    src/pages/index.tsx-->src/pages/MetricsExplorerPage.tsx
    src/pages/index.tsx-->src/pages/PlayerPage.tsx
    src/pages/index.tsx-->src/pages/PlayersPage.tsx
    src/pages/index.tsx-->src/pages/SchemaVisualizerPage.tsx
    src/pages/index.tsx-->src/pages/ScrimPage.tsx
    src/pages/index.tsx-->src/pages/ScrimsPage.tsx
    src/pages/index.tsx-->src/pages/TeamPage.tsx
    src/pages/index.tsx-->src/pages/TeamsPage.tsx
    src/App.tsx-->src/pages/index.tsx
    src/App.tsx-->src/components/index.ts
    src/index.tsx-->src/App.tsx
    src/atoms/killMatrix.ts-->src/atoms/index.ts
    src/atoms/killMatrix.ts-->src/lib/index.ts
    src/atoms/playerComparisonAtomFamily.ts-->src/lib/index.ts
    src/atoms/playerComparisonAtomFamily.ts-->src/atoms/index.ts
    src/atoms/playerListSummary.ts-->src/atoms/index.ts
    src/atoms/playerListSummary.ts-->src/lib/index.ts
    src/atoms/playerMatchHistoryAtom.ts-->src/atoms/index.ts
    src/atoms/playerStatExpandedAtom.ts-->src/atoms/index.ts
    src/atoms/playerStatExpandedAtom.ts-->src/lib/index.ts
    src/atoms/segmentStatsAtomFamily.ts-->src/atoms/index.ts
    src/atoms/teamCompositionsAtom.ts-->src/atoms/index.ts
    src/atoms/ultimateImpactAtom.ts-->src/atoms/index.ts
    src/atoms/uniqueGameModesAtom.ts-->src/atoms/index.ts
    src/lib/playerEvents.ts-->src/lib/index.ts
