name: Check Build

on:
  pull_request:
    branches: [ prod ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16 # Or your preferred Node.js version
          cache: 'npm'
      - run: npm ci
      - run: npm run build